# Automatic deployment to a dev environment on every push to helm_deploy.
dev:
  auto_deploy_on: refs/heads/helm_deploy
  required_contexts: ["build"]
  environment: dev
  description: 'Dev'
  payload:
    value_files: ["./config/dev.yml", "./config/_common.yml"]
    namespace: 'nha'
    track: stable
    values:
      replicaCount: 1
