version: '3'
services:
  client-registry:
    build: .
    ports:
      - "8080:8080"
    environment:
      - profile=local
    networks:
      - client-registry
networks:
  client-registry:
    driver: bridge
    external: false