version: '3'
services:
  client-registry:
    image: "ganesan92/client-registry:${CR_IMAGE_TAG}"
    ports:
      - "8080:8080"
    environment:
      - profile=dev
    networks:
      - client-registry
networks:
  client-registry:
    driver: bridge
    external: false